[package]
name = "simple_llama"
version = "1.1.0"
edition = "2024"
description = "A simple AI library."
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.44.0", features = ["full"]  } 
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
reqwest = { version = "0.12.12", features = ["json"] }